### ISSUE TITLE
--color not working in 1.0.7 version

### ISSUE THREAD

**Issue by eribertomota** [cslarsen/jp2a#6]
Hi Christian,

I don't tested other options but --color is not working in 1.0.7 version.

Can you fix it until November 15 to allow upload to Debian before freeze and allow jp2a in new Debian release?

Regards,

Eriberto

**Comment by eribertomota** [comment]
Hum... Now, I saw that this bug is identical to #2. Sorry. I will wait a fix to upload to Debian.

**Comment by cslarsen** [comment]
Yep, it's been ages since I take a good look at this code. Seems I'm not even using colors at all with the code as it is. Will have a look.

**Comment by cslarsen** [comment]
What's going on is that when the code was hosted on SourceForge, I did not use branches, and I've obviously been doing experimental changes directly on master. Or I did, but the conversion script didn't take that into account. It means that the changes since v1.0.6, 46a22d62b1b5dc743be37d58d1f72928de2a0327, are most likely broken. Not sure what I'll do, but I might just nuke the changes since that and apply good changes on top of 1.0.6.

**Comment by eribertomota** [comment]
I suggest to release a 1.0.8 version reverting all bad changes and fixing
the #3. In this moment, all distros have a problem: a broken release
(1.0.7). Can you solve it?

If you want, I can test the code in Debian before you tag 1.0.8.

Thanks a lot in advance.

Regards,

Eriberto

2016-11-01 17:43 GMT-02:00 Christian Stigen Larsen <notifications@github.com

**Comment by cslarsen** [comment]
Ok Eriberto, if you have time, can you give this a try? I just reverted straight down to 1.0.6 and made a few small changes on top.

If this works, I can create a tag, meaning you'll get a downloadable .tar.gz file that you can refer to (I'm not sure how to actually add the autoconf output files there, though).

**Comment by eribertomota** [comment]
Hi,

2016-11-07 17:40 GMT-02:00 Christian Stigen Larsen <notifications@github.com

> :
> 
> Ok Eriberto, if you have time, can you give this a try? I just reverted
> straight down to 1.0.6 and made a few small changes on top.

Tested. The --color option works. However, this bug[1] still unsolved.

[1] https://bugs.launchpad.net/ubuntu/+source/jp2a/+bug/1252209

If this works, I can create a tag, meaning you'll get a downloadable

> .tar.gz file that you can refer to

Ok!

> (I'm not sure how to actually add the autoconf output files there, though).

I didn't understand. Can you elaborate?

Cheers,

Eriberto

**Comment by cslarsen** [comment]
As for the bug, it's probably hanging forever in the aspect ratio function. I'll have a look later. 

The autoconf files; to make a proper release, you need to run "autoreconf -vi" to produce the `configure` script and supporting files. But I think I can just make a release branch and put the files there, then tag that, and there will be a .tar.gz / .zip with those files in it.

Would you care to report that bug in a separate issue? It's because I want to close this one.

**Comment by cslarsen** [comment]
Ok Eriberto, I see you've already posted another issue for that bug. Thanks, will have a look at it.

**Comment by eribertomota** [comment]
About autoreconf, the Debian build system allow to use it. See here[1](dh $@ --with autoreconf).

I suggest create a autogen.sh for trivial users. Several upstreams does it. There are three examples here[2][3][4].

[1] https://sources.debian.net/src/jp2a/1.0.7-1/debian/rules/
[2] http://sources.debian.net/src/iptables/1.6.0-4/autogen.sh/?hl=3#L3
[3] http://sources.debian.net/src/libvncserver/0.9.10%2Bdfsg-3/autogen.sh/?hl=3#L3
[4] https://github.com/eribertomota/axel/blob/master/autogen.sh

Cheers,

Eriberto
